### ISSUE TITLE
真的不考虑把这个框架给整理下吗？

### ISSUE THREAD

**Issue by lmxyy** [fzls/dnf_calc#1]
我读了下目前的代码，感觉所有东西都写在一个4000行文件里，可读性不高，并且pycharm解析都要半天。不考虑下找个时间把代码整理下，分成几个modules，并且面向对象编程吗？这样以后更新也更方便，不然的话历史包袱会越来越大。

**Comment by fzls** [comment]
暂时还在做新功能=、=下一步就是重构代码啦

**Comment by fzls** [comment]
毕竟事情得一步步来，刚开始就想尽善尽美的话最终可能啥也做不了哈哈

**Comment by fzls** [comment]
目前对原版做的主要改动基本是
1. 启动优化&性能优化
2. 添加额外方便使用的功能
3. 做一些ui和使用方便性的改动
4. 抽取国服特色

**Comment by lmxyy** [comment]
I see. 过几天我有时间了，可以帮忙重构下。之前更新的太勤了，每次重构到一半，新版本就release了。此外，我还发现，非win7下(win10, macOS)下的ui好像有些问题，部分构件有重合。

**Comment by fzls** [comment]
win10下没啥问题呀，我日常用win10，目前已知的情况是修改过系统字体缩放后，ui展示会重合= =

**Comment by fzls** [comment]
那一坨恐怖的ui拼接代码和各个地方可以看到的奇怪命名的字段，还是一些似乎通过代码生成器生成的a,b,c,d等并无实际作用的变量，我每次看到也感到很难受，但是考虑到时间精力有限，都是强忍着先放一边。目前基本该做的都做得差不多了，这周差不多开始进行代码清理了~

**Comment by fzls** [comment]
![Snipaste_2020-05-12_00-32-08](https://user-images.githubusercontent.com/13483212/81586410-08f21500-93e8-11ea-9779-85307f03dc47.png)

**Comment by fzls** [comment]
你看我在4.17就在onenote中备注了各种需要重构的地方，但是一直在做想到和吧友反馈的一些新功能和bug修复，一直没有时间重构哈哈

**Comment by lmxyy** [comment]
辛苦了

**Comment by fzls** [comment]
不过这些其实都是细枝小节，目前我做下来感觉最需要优化的其实是两点：
1. 找到一个更精确且计算代价也不会太高的预估函数用于更精确的剪枝。目前的根据套装词条数目来判定价值量的预估函数很容易将一些实际更好的搭配给过滤掉
2. 完善核心计算模型，现在的模型中至少我已知的就是技能这块分的有些粗，比如1-45技能划到一起，这使得buff称号等只增加特定技能或特定等级的技能无法很好地被量化。

但是上面两点都需要对游戏的伤害和奶量计算有着比较深的理解，而这一点是我所欠缺的。所以暂时做的都是偏程序方向的改动。

**Comment by fzls** [comment]
上面第一点，现在的预估函数很明显没有将当前的搭配各个装备本身的词条和属性给考虑进来，这就导致一些单件很强的搭配，在这一步会比较吃亏

**Comment by Zwlin98** [comment]
有没有兴趣做成网页客户端呢，我可以帮忙

**Comment by fzls** [comment]
> 有没有兴趣做成网页客户端呢，我可以帮忙

这个主要是没有服务器哈哈哈，而且改成网页端ui侧还是挺繁琐的- -现在colg那边有几个网页版的了吧~
