### ISSUE TITLE
奶系职业荣誉和太阳适配体力、智力不一样。

### ISSUE THREAD

**Issue by Skyearn** [fzls/dnf_calc#17]
尝试了 3.3 以后的所有版本均有此问题。舍弃所有可能的干扰，新选择随机防具首饰特殊也会出现同样的问题。清空统一自定义定义国服特色也是一样的问题。
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/29571915/82281454-ee113900-99c3-11ea-8df8-c5d8f49e4199.png">

**Comment by fzls** [comment]
=、=韩械的3.2版本没问题吗

**Comment by Skyearn** [comment]
> =、=韩械的3.2版本没问题吗

哇，回复好快，我目前只有 3.3 以后的版本。因为韩械的版本性能比较低删掉了……

**Comment by fzls** [comment]
那估计它的也有问题=、=我其实没对奶的改太多。。。。。可能是原版计算模型的问题吧- -

**Comment by Skyearn** [comment]
> 那估计它的也有问题=、=我其实没对奶的改太多。。。。。可能是原版计算模型的问题吧- -

我在群历史文件找到了韩械 3.2 的版本，确实也是存在适用不一样的情况，以前没注意到，最近两个版本需要自定义才发现。而且并不是差的统一的数值，有些装备可能是 40 点，有些可能 44 点这样。
<img width="633" alt="image" src="https://user-images.githubusercontent.com/29571915/82281950-409f2500-99c5-11ea-90dd-e328243c3e5f.png">

**Comment by fzls** [comment]
是不是角色四维光环啥的- -

**Comment by Skyearn** [comment]
> 是不是角色四维光环啥的- -

应该不是，我有过自定义国服特色，也是一样。而且不同装备下差异数值不一，估计是原版计算模型的问题。

**Comment by fzls** [comment]
哦，早上没细看，我刚看了下原来你说的是荣誉和太阳的适用智力，这俩本来就是不一样的= =[
![Snipaste_2020-05-10_21-33-46](https://user-images.githubusercontent.com/13483212/82297205-e57d2a80-99e4-11ea-8251-4f4880b4aa8b.png)
](url)

**Comment by fzls** [comment]
你去帝国竞技场里用奶和输出一起进去，放完buff切输出看面板，这俩的是用智力/体力本来就是差40左右的

**Comment by Skyearn** [comment]
> 你去帝国竞技场里用奶和输出一起进去，放完buff切输出看面板，这俩的是用智力/体力本来就是差40左右的

是一样的哦。我是开小号在修炼场测试的。登记的装备和身上穿的装备只有时装上衣和称号的差别。登记的 3 级荣誉的称号，1 级荣誉的时装上衣。穿的 2 级太阳的称号，1 级太阳的时装上衣。

<img width="304" alt="image" src="https://user-images.githubusercontent.com/29571915/82299191-caf88080-99e7-11ea-87ac-3741ee803b1a.png">
<img width="282" alt="image" src="https://user-images.githubusercontent.com/29571915/82299198-cd5ada80-99e7-11ea-99d8-b4041990bccc.png">

**Comment by fzls** [comment]
不清楚诶，我用奶妈玩都是有区别的-。-

**Comment by Skyearn** [comment]
> 不清楚诶，我用奶妈玩都是有区别的-。-

登记的装备和穿的智力有差异就有区别，不登记就没区别。

**Comment by Skyearn** [comment]
> 不清楚诶，我用奶妈玩都是有区别的-。-

如果大佬能跟作者反馈下最好，不行的话我手动补正下也能用……

**Comment by Skyearn** [comment]
找到问题了，计算太阳适用体精时额外加了三级 15 级转职被动。
<img width="907" alt="image" src="https://user-images.githubusercontent.com/29571915/82964452-11596b00-9ff8-11ea-8c04-98d8ac9f2cd1.png">
