### ISSUE TITLE
过多的装备会导致计算失败吗？

### ISSUE THREAD

**Issue by x1zbin** [fzls/dnf_calc#19]
![image](https://user-images.githubusercontent.com/25758203/82876426-597e7c00-9f6b-11ea-982c-d6586eae842c.png)
添加当前角色的所有百级装备后，计算了很久了，剩余时间一直0，然后有效搭配还在一直增加。感觉有效搭配没有这么多，是不是过多数据会导致前面计算结果被刷走然后认为没被计算而一直重复计算？

**Comment by fzls** [comment]
不会，建议你打开日志目录看看是否有异常报错日志

**Comment by x1zbin** [comment]
发现是选择了“超慢速”后。。就会时间估算错误。。好吧，看来是我低估了这个“超慢速”

**Comment by fzls** [comment]
> 发现是选择了“超慢速”后。。就会时间估算错误。。好吧，看来是我低估了这个“超慢速”

是个确实很慢的，会老老实实计算每一个组合= =，不做任何剪枝和预估
