### ISSUE TITLE
3.4.3增加完国服特色后计算差异巨大，不配置国服特色算出来得结果和之前得也有较大差距

### ISSUE THREAD

**Issue by YohannHe** [fzls/dnf_calc#2]

**Comment by fzls** [comment]
=。=你是不是没有把原来的自定义中的国服特色（指各种属强、奶的数据）给干掉？

我自己这几个版本用过来感觉没啥差异诶=、=基本都符合我的预期，尤其是把原有的顶配特色去掉，改为自定义后感觉比原来要准一些- -

**Comment by fzls** [comment]
另外今天赞赏码里面说加个好友的应该是你吧~  
赞赏码不能对对方回复任何东西，除了名字和留言，看不到其他信息，所以没法回复。
刚刚看到邮件提示，发现你这名字有点眼熟，对比了下果然是，我把二维码发这里吧0-0

**Comment by fzls** [comment]
![mmqrcode1589214257501](https://user-images.githubusercontent.com/13483212/81585888-5752e400-93e7-11ea-858c-37922ac33418.png)

**Comment by RivenPlayer-1** [comment]
请问如何下载最新版本？输入fzls后显示密码不正确

**Comment by fzls** [comment]
@RivenPlayer-1 蓝奏云https://fzls.lanzous.com/s/dnf-calc，提取码fzls

**Comment by RivenPlayer-1** [comment]
@fzls 我是想下4.12版本的计算机，但是密码不是fzls

**Comment by fzls** [comment]
@RivenPlayer-1  你一提我想起来了= =蓝奏云子目录还得单独设密码，不然默认是乱码。。。我还是不用子目录了哈哈。稍等一下，我去改一下

**Comment by RivenPlayer-1** [comment]
@fzls 百度网盘的被禁了

**Comment by RivenPlayer-1** [comment]
@fzls 嗯，谢谢

**Comment by fzls** [comment]
@RivenPlayer-1 百度网盘老是抽风，下载还限速，已经弃用了，现在用蓝奏云发布
