### ISSUE TITLE
龙血玄黄在实际计算时，并没有应用到自定义中的角色熟练度等级

### ISSUE THREAD

**Issue by ChieloNewctle** [fzls/dnf_calc#20]
代码里是把 `db_save_one` 改了，但是单件之类的信息没用到这个，实际测试了一下也确实属强等多了一点。

**Comment by fzls** [comment]
是直接在保存时将赌赢熟练度的数值保存到装备表中，具体可见下面代码，所以计算时就已经是应用后的数值了

![image](https://user-images.githubusercontent.com/13483212/82934793-a9d2f980-9fbe-11ea-83ba-6232015de63e.png)

**Comment by ChieloNewctle** [comment]
了解了，我更新后复制了preset没复制data。。保存一次自定义就好了。
