### ISSUE TITLE
开启进程过多（？）导致的崩溃

### ISSUE THREAD

**Issue by MeoRean** [fzls/dnf_calc#32]
CPU是3900X，根据现有规则会开启4*24=96个进程，然后打开时就会报错，而且是系统级的，可能导致系统里的其他的程序也崩溃，如图

![b](https://user-images.githubusercontent.com/32858333/83972594-9e16f980-a913-11ea-8695-1c2d3b0e696c.png)
修改config.py，去掉倍数，只开启24个进程，就没问题

**Comment by fzls** [comment]
嗯嗯，这个默认是配置了四倍线程数的进程= =可以自己调一下~

**Comment by fzls** [comment]
下图是今天凌晨测试不同线程数的测试结果。根据这个我设置了四倍线程数= =
![Snipaste_2020-06-07_23-11-30](https://user-images.githubusercontent.com/13483212/83972708-44fb9580-a914-11ea-99dc-10db0c8843ae.png)

**Comment by fzls** [comment]
我下个版本的默认值加个上限吧，比如32，如果默认计算出大于这个就截断，但是手动配置大于这个则不截断
