### ISSUE TITLE
计算中退出进程残留问题

### ISSUE THREAD

**Issue by x1zbin** [fzls/dnf_calc#34]
![image](https://user-images.githubusercontent.com/25758203/84221219-49d46b00-ab07-11ea-8b84-9ea079f8c05f.png)

计算过慢点击停止，提示直接关闭。关闭后有进程残留，原本是3个的，其中一个cpu占用85%+。杀掉了才想起来截图。

**Comment by x1zbin** [comment]
而且退出了超过8小时了。

**Comment by fzls** [comment]
啥版本？

**Comment by x1zbin** [comment]
v3.5.8

**Comment by fzls** [comment]
> v3.5.8

试试3.6.6
