### ISSUE TITLE
全亮 快速 大骨戒天下第一？

### ISSUE THREAD

**Issue by Pyrokine** [fzls/dnf_calc#35]
切到慢速 算了一个小时之后告诉我还有14个小时 并且 时间还在增加！猴戏呢 吃了10g运存 然后点停止还说只能关闭？

**Comment by fzls** [comment]
不如先理解下这几个不同速度的含义？

**Comment by Pyrokine** [comment]
连提供正确的结果都做不到 还算啥呢

**Comment by Pyrokine** [comment]
如果提供错误的结果 再快有什么意义

**Comment by fzls** [comment]
> 如果提供错误的结果 再快有什么意义

这里是反馈bug的，不自己去了解对应选项是干嘛的就来瞎喷，这边不欢迎这种。

顺带跟你说，快速是指仅考虑成套的搜索方案，中速按照套装词条数过滤掉一些搜索方案，降低计算量。慢速是指考虑套装词条数比历史最高词条数低1的搜索方案，计算级会高出几个数量级，计算一天都不算什么。如果你对计算几万亿的搭配没有概念的话，建议去学学高中数学。最后超慢速是不做任何剪枝和预估，计算所有搭配。

最后一句，不知道github有没有黑名单，要是有的话我第一个把你这种不管三七二十一上来一顿喷，不看看是不是自己的问题的人给放进去。代码都在那，跑来跟我这一顿瞎喷，谁鸟你啊。

我就你上面这几个一一回答一遍。
1. 全亮快速结果就是那样。不信你自己手动算每一个套装的属性。欢迎杠精慢慢算。别张口就来答案是错的。
2. 慢速就是这么慢，计算量级跟中速和快速完全不能比，目前相对于最开始魔改之前的版本已经快了不知道多少倍。你觉得速度慢或者答案有问题，欢迎指出哪里代码有问题，都会用github了，还在这瞎喷，真丢人。
3. 你觉得这是猴戏，速度慢，欢迎你整个速度更快结果更精确的版本出来，做不到就别在这喷粪。
4. 不允许停止怎么了？你关掉再打开觉得很费事？那不能自己做个版本出来？改动说明里写的清清楚楚，多进程环境下考虑计算性能，废弃了停止功能，自己不看，在这瞎喷。
5. 正确的结果做不到，你指什么是正确？知道什么叫精确性和速度的取舍吗？你要精确和正确，那你为啥不用最慢速？觉得计算太慢？那你说个j8。又想要精确，又想要速度快，天下哪有这么好的事情。
6. 提供错误的结果，我特么说的清清楚楚，让你自己根据精确性要求去选择不同的速度，自己不会用，搁这喷？

**Comment by fzls** [comment]
talk is cheap, show me the code。既然是个程序员，做事起码有些证据。自己的言论至少要找出对应的代码来支撑。

**Comment by fzls** [comment]
另外这是免费魔改的，善意分享出来。你爱用不用，没人求你来用。
提出一堆似是而非的问题，没见你有一丝丝的分析或者提供任意可能的解决思路，呵呵。
没做出一点点贡献，只会在这瞎喷，真的令人无语。

**Comment by fzls** [comment]
> 如果提供错误的结果 再快有什么意义

最后你觉得本身这个计算器提供多种速度方案是有问题的，欢迎你去找韩服作者去喷。我魔改爱改啥改啥，我觉得韩服作者这个设定很ok。

希望下周能看到你改出一版能够计算所有搭配方案，不过滤任何方案，同时速度非常快的计算器出来。如果你做不到一个小时内把所有的搭配方案都计算出来，就别来丢人现眼了。

**Comment by fzls** [comment]
已block，勿回 :(

**Comment by fzls** [comment]
看了下，你也做过网页版的计算器。那你不至于不清楚速度和精确度的权衡吧？

**Comment by pyrokinetech** [comment]
把人ban了还能说啥，知道你还要ban我，那我一次性多说一点，我的言论当然能用我的结果来支撑，不需要下周，现在就欢迎移步https://pyro.cafe尝试，虽然我不开源。你的代码我是大概看了一遍的，起码，我不会提供一个毫无意义的结果，指你的快速结果，大骨戒天下第一？中速结果也是大骨戒+未来耳环，不信你可以试试，全亮+中速不偏好计算出来的结果是大自然+狂乱+深渊+未来耳环+大骨戒，你确定这个结果有任何意义吗，如果没有意义，那么全亮这个按钮有什么用，以及快速和中速有什么用？选择了智慧的产物发现了问题，绝大部分人不会选择这个，真的能发现算法的不可靠性吗？
我能在3.4ghz单核2g内存上并行四个运算用1k行的前后端在半天内提供结果，且计算时间中位数平均数不超过半小时，我当然能质疑你的结果的精确性了，你这个计算器我本地运算，算了一个多小时还要十几个小时，时间还在增加？那这预估时间有什么用？85%cpu占用，10G内存占用，并且内存还之会更大，你确定你这代码和韩版的有任何区别吗？并且，我的计算是不过滤任何套装的，所有套装一视同仁，此外，我没有使用原计算器的数据，所有数据我都是从游戏里一个一个统计出来的，所以你不用担心我的工作量问题，因此，结果出现错误欢迎你发起issue，我能溯源所有结果☺

**Comment by fzls** [comment]
> 把人ban了还能说啥，知道你还要ban我，那我一次性多说一点，我的言论当然能用我的结果来支撑，不需要下周，现在就欢迎移步[https://pyro.cafe尝试，虽然我不开源。你的代码我是大概看了一遍的，起码，我不会提供一个毫无意义的结果，指你的快速结果，大骨戒天下第一？中速结果也是大骨戒+未来耳环，不信你可以试试，全亮+中速不偏好计算出来的结果是大自然+狂乱+深渊+未来耳环+大骨戒，你确定这个结果有任何意义吗，如果没有意义，那么全亮这个按钮有什么用，以及快速和中速有什么用？选择了智慧的产物发现了问题，绝大部分人不会选择这个，真的能发现算法的不可靠性吗？](https://pyro.cafe%E5%B0%9D%E8%AF%95%EF%BC%8C%E8%99%BD%E7%84%B6%E6%88%91%E4%B8%8D%E5%BC%80%E6%BA%90%E3%80%82%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E6%88%91%E6%98%AF%E5%A4%A7%E6%A6%82%E7%9C%8B%E4%BA%86%E4%B8%80%E9%81%8D%E7%9A%84%EF%BC%8C%E8%B5%B7%E7%A0%81%EF%BC%8C%E6%88%91%E4%B8%8D%E4%BC%9A%E6%8F%90%E4%BE%9B%E4%B8%80%E4%B8%AA%E6%AF%AB%E6%97%A0%E6%84%8F%E4%B9%89%E7%9A%84%E7%BB%93%E6%9E%9C%EF%BC%8C%E6%8C%87%E4%BD%A0%E7%9A%84%E5%BF%AB%E9%80%9F%E7%BB%93%E6%9E%9C%EF%BC%8C%E5%A4%A7%E9%AA%A8%E6%88%92%E5%A4%A9%E4%B8%8B%E7%AC%AC%E4%B8%80%EF%BC%9F%E4%B8%AD%E9%80%9F%E7%BB%93%E6%9E%9C%E4%B9%9F%E6%98%AF%E5%A4%A7%E9%AA%A8%E6%88%92+%E6%9C%AA%E6%9D%A5%E8%80%B3%E7%8E%AF%EF%BC%8C%E4%B8%8D%E4%BF%A1%E4%BD%A0%E5%8F%AF%E4%BB%A5%E8%AF%95%E8%AF%95%EF%BC%8C%E5%85%A8%E4%BA%AE+%E4%B8%AD%E9%80%9F%E4%B8%8D%E5%81%8F%E5%A5%BD%E8%AE%A1%E7%AE%97%E5%87%BA%E6%9D%A5%E7%9A%84%E7%BB%93%E6%9E%9C%E6%98%AF%E5%A4%A7%E8%87%AA%E7%84%B6+%E7%8B%82%E4%B9%B1+%E6%B7%B1%E6%B8%8A+%E6%9C%AA%E6%9D%A5%E8%80%B3%E7%8E%AF+%E5%A4%A7%E9%AA%A8%E6%88%92%EF%BC%8C%E4%BD%A0%E7%A1%AE%E5%AE%9A%E8%BF%99%E4%B8%AA%E7%BB%93%E6%9E%9C%E6%9C%89%E4%BB%BB%E4%BD%95%E6%84%8F%E4%B9%89%E5%90%97%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%B2%A1%E6%9C%89%E6%84%8F%E4%B9%89%EF%BC%8C%E9%82%A3%E4%B9%88%E5%85%A8%E4%BA%AE%E8%BF%99%E4%B8%AA%E6%8C%89%E9%92%AE%E6%9C%89%E4%BB%80%E4%B9%88%E7%94%A8%EF%BC%8C%E4%BB%A5%E5%8F%8A%E5%BF%AB%E9%80%9F%E5%92%8C%E4%B8%AD%E9%80%9F%E6%9C%89%E4%BB%80%E4%B9%88%E7%94%A8%EF%BC%9F%E9%80%89%E6%8B%A9%E4%BA%86%E6%99%BA%E6%85%A7%E7%9A%84%E4%BA%A7%E7%89%A9%E5%8F%91%E7%8E%B0%E4%BA%86%E9%97%AE%E9%A2%98%EF%BC%8C%E7%BB%9D%E5%A4%A7%E9%83%A8%E5%88%86%E4%BA%BA%E4%B8%8D%E4%BC%9A%E9%80%89%E6%8B%A9%E8%BF%99%E4%B8%AA%EF%BC%8C%E7%9C%9F%E7%9A%84%E8%83%BD%E5%8F%91%E7%8E%B0%E7%AE%97%E6%B3%95%E7%9A%84%E4%B8%8D%E5%8F%AF%E9%9D%A0%E6%80%A7%E5%90%97%EF%BC%9F)
> 我能在3.4ghz单核2g内存上并行四个运算用1k行的前后端在半天内提供结果，且计算时间中位数平均数不超过半小时，我当然能质疑你的结果的精确性了，你这个计算器我本地运算，算了一个多小时还要十几个小时，时间还在增加？那这预估时间有什么用？85%cpu占用，10G内存占用，并且内存还之会更大，你确定你这代码和韩版的有任何区别吗？并且，我的计算是不过滤任何套装的，所有套装一视同仁，此外，我没有使用原计算器的数据，所有数据我都是从游戏里一个一个统计出来的，所以你不用担心我的工作量问题，因此，结果出现错误欢迎你发起issue，我能溯源所有结果☺

你知道改五的骨戒是啥强度吗？张口就来这个结果没有意义

**Comment by fzls** [comment]
> 把人ban了还能说啥，知道你还要ban我，那我一次性多说一点，我的言论当然能用我的结果来支撑，不需要下周，现在就欢迎移步[https://pyro.cafe尝试，虽然我不开源。你的代码我是大概看了一遍的，起码，我不会提供一个毫无意义的结果，指你的快速结果，大骨戒天下第一？中速结果也是大骨戒+未来耳环，不信你可以试试，全亮+中速不偏好计算出来的结果是大自然+狂乱+深渊+未来耳环+大骨戒，你确定这个结果有任何意义吗，如果没有意义，那么全亮这个按钮有什么用，以及快速和中速有什么用？选择了智慧的产物发现了问题，绝大部分人不会选择这个，真的能发现算法的不可靠性吗？](https://pyro.cafe%E5%B0%9D%E8%AF%95%EF%BC%8C%E8%99%BD%E7%84%B6%E6%88%91%E4%B8%8D%E5%BC%80%E6%BA%90%E3%80%82%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%A0%81%E6%88%91%E6%98%AF%E5%A4%A7%E6%A6%82%E7%9C%8B%E4%BA%86%E4%B8%80%E9%81%8D%E7%9A%84%EF%BC%8C%E8%B5%B7%E7%A0%81%EF%BC%8C%E6%88%91%E4%B8%8D%E4%BC%9A%E6%8F%90%E4%BE%9B%E4%B8%80%E4%B8%AA%E6%AF%AB%E6%97%A0%E6%84%8F%E4%B9%89%E7%9A%84%E7%BB%93%E6%9E%9C%EF%BC%8C%E6%8C%87%E4%BD%A0%E7%9A%84%E5%BF%AB%E9%80%9F%E7%BB%93%E6%9E%9C%EF%BC%8C%E5%A4%A7%E9%AA%A8%E6%88%92%E5%A4%A9%E4%B8%8B%E7%AC%AC%E4%B8%80%EF%BC%9F%E4%B8%AD%E9%80%9F%E7%BB%93%E6%9E%9C%E4%B9%9F%E6%98%AF%E5%A4%A7%E9%AA%A8%E6%88%92+%E6%9C%AA%E6%9D%A5%E8%80%B3%E7%8E%AF%EF%BC%8C%E4%B8%8D%E4%BF%A1%E4%BD%A0%E5%8F%AF%E4%BB%A5%E8%AF%95%E8%AF%95%EF%BC%8C%E5%85%A8%E4%BA%AE+%E4%B8%AD%E9%80%9F%E4%B8%8D%E5%81%8F%E5%A5%BD%E8%AE%A1%E7%AE%97%E5%87%BA%E6%9D%A5%E7%9A%84%E7%BB%93%E6%9E%9C%E6%98%AF%E5%A4%A7%E8%87%AA%E7%84%B6+%E7%8B%82%E4%B9%B1+%E6%B7%B1%E6%B8%8A+%E6%9C%AA%E6%9D%A5%E8%80%B3%E7%8E%AF+%E5%A4%A7%E9%AA%A8%E6%88%92%EF%BC%8C%E4%BD%A0%E7%A1%AE%E5%AE%9A%E8%BF%99%E4%B8%AA%E7%BB%93%E6%9E%9C%E6%9C%89%E4%BB%BB%E4%BD%95%E6%84%8F%E4%B9%89%E5%90%97%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%B2%A1%E6%9C%89%E6%84%8F%E4%B9%89%EF%BC%8C%E9%82%A3%E4%B9%88%E5%85%A8%E4%BA%AE%E8%BF%99%E4%B8%AA%E6%8C%89%E9%92%AE%E6%9C%89%E4%BB%80%E4%B9%88%E7%94%A8%EF%BC%8C%E4%BB%A5%E5%8F%8A%E5%BF%AB%E9%80%9F%E5%92%8C%E4%B8%AD%E9%80%9F%E6%9C%89%E4%BB%80%E4%B9%88%E7%94%A8%EF%BC%9F%E9%80%89%E6%8B%A9%E4%BA%86%E6%99%BA%E6%85%A7%E7%9A%84%E4%BA%A7%E7%89%A9%E5%8F%91%E7%8E%B0%E4%BA%86%E9%97%AE%E9%A2%98%EF%BC%8C%E7%BB%9D%E5%A4%A7%E9%83%A8%E5%88%86%E4%BA%BA%E4%B8%8D%E4%BC%9A%E9%80%89%E6%8B%A9%E8%BF%99%E4%B8%AA%EF%BC%8C%E7%9C%9F%E7%9A%84%E8%83%BD%E5%8F%91%E7%8E%B0%E7%AE%97%E6%B3%95%E7%9A%84%E4%B8%8D%E5%8F%AF%E9%9D%A0%E6%80%A7%E5%90%97%EF%BC%9F)
> 我能在3.4ghz单核2g内存上并行四个运算用1k行的前后端在半天内提供结果，且计算时间中位数平均数不超过半小时，我当然能质疑你的结果的精确性了，你这个计算器我本地运算，算了一个多小时还要十几个小时，时间还在增加？那这预估时间有什么用？85%cpu占用，10G内存占用，并且内存还之会更大，你确定你这代码和韩版的有任何区别吗？并且，我的计算是不过滤任何套装的，所有套装一视同仁，此外，我没有使用原计算器的数据，所有数据我都是从游戏里一个一个统计出来的，所以你不用担心我的工作量问题，因此，结果出现错误欢迎你发起issue，我能溯源所有结果☺

你知道改五的骨戒是啥强度吗？张口就来这个结果没有意义

**Comment by pyrokinetech** [comment]
一起来看到有人回复说让你把骂人的话都删掉，然后紧接着我就被封号了，哎呦，真的笑死个人，一会儿你把我这个号也拉黑好了，反正也是刚创的小号，这样死人就不用说话了，xswl，骂人的把yygq的举报了，真的非常6了  
因为听了几句yygq，就说自己可以无下限的骂人，在网上装啥衣冠禽兽呢？这种人真的有意思，那我只能真的感激您为github语言纯洁性做出了不可磨灭的贡献了，风大善人  
我说你慢速有问题，我说过你至今的努力一文不值吗？要不给您来首希望之花？你说慢速没问题？来个benchmark？我花了几分钟把我的代码改成了慢速计算的方式，就几行的区别，实测一个小时也就68.8MB的内存占用，要不给您录个屏？反正结果肯定是算不出来的，但是我的内存占用就是小，我在这给你打字时一点都不卡，你的那个魔改版慢速开了之后电脑还能用吗？不如自己开个24小时试试嘛，当然，这时候您肯定又要说到让我去看您的代码，看您做了什么工作，然而我只关心卡不卡，就像tp和游戏服务器一样，我说他卡，有问题，难道我还要去看懂他的代码然后提出意见才能说话？怎么不把泥潭贴子全删了呢  
说什么半途而废，你有你的想法，我有我的工作，我也有长期维护的代码，何必面面俱到地告诉您呢？真的非常可笑

**Comment by pyrokinetech** [comment]
此外，又看了一遍你的贴子，你的粉丝也都在那yygq嘛，都是行家，装啥白莲花

**Comment by fzls** [comment]
自己先阴阳怪气就别来别来丢人现眼了。自己说不过别人又来骂街？拜拜了您。被封号也不管我任何事，说明版主也觉得你的为人处世有问题，明眼人都清楚

**Comment by fzls** [comment]
事实上你这种人想什么我都不想管，大道两边格子一边，你爱干嘛干嘛，别来我这边撒野就完事咯。
我可没举报你，别瞎给你戴帽子哦。

**Comment by fzls** [comment]
骂人，那也得骂的是人。您看看您issue开头几句表现的是人吗？我从不骂人的哦。

**Comment by fzls** [comment]
在colg、贴吧、反馈群的计算器相关内容中，你可以说是我仅有的骂过的人了。自己不表现的像个人一样，就别怪别人不把你当人。

**Comment by fzls** [comment]
顺带说下你所谓的内存占用问题，但凡你仔细看过代码或者有点好奇去看看日志都不会问出这样的问题。
你的内存小，是因为你是用单线程计算，每计算出一个结果就进行排行。内存占用与排行数目（如5个）成正比。事实上魔改版单线程时也是这样。你这种处理办法，别说14个小时，哪怕一年都不一定算的完。

魔改的多进程版本内存占用大，是因为采用了多进程计算框架。计算逻辑是在若干个工作进程中跑，但是排行逻辑是通过各个工作进程将每个搭配的计算结果通过队列传回来。目前在八核心的cpu上，使用16个工作进程时，测试时排行速度大概是计算结果产生速度的百分之一。因此待排行的计算结果队列会越来越大，内存会慢慢长大。在目前没有找到比堆排序更优的固定大小排行算法前，这个问题没啥好方法解决。即使开多个排行线程，最后整合结果，也只是常数级提升，还是无法与计算结果产生速度匹配。

总结一下，所谓我的我的慢速慢，你的慢速快，只是你理解有问题，事实上我的比你的要远快，而且正确性我也敢保证。计算器的目的是算的更快，给出结果。而不是内存小，算的慢。别拿半吊子水平出来搞笑。

**Comment by fzls** [comment]
另外，你的计算器不是不卡，是做不到让电脑变卡。如果想要不卡，自然可以把工作进程数改为1，保证不卡。但是你的呢，你有本身就把全部核心都占满来计算？

**Comment by fzls** [comment]
> 一起来看到有人回复说让你把骂人的话都删掉，然后紧接着我就被封号了，哎呦，真的笑死个人，一会儿你把我这个号也拉黑好了，反正也是刚创的小号，这样死人就不用说话了，xswl，骂人的把yygq的举报了，真的非常6了
> 因为听了几句yygq，就说自己可以无下限的骂人，在网上装啥衣冠禽兽呢？这种人真的有意思，那我只能真的感激您为github语言纯洁性做出了不可磨灭的贡献了，风大善人
> 我说你慢速有问题，我说过你至今的努力一文不值吗？要不给您来首希望之花？你说慢速没问题？来个benchmark？我花了几分钟把我的代码改成了慢速计算的方式，就几行的区别，实测一个小时也就68.8MB的内存占用，要不给您录个屏？反正结果肯定是算不出来的，但是我的内存占用就是小，我在这给你打字时一点都不卡，你的那个魔改版慢速开了之后电脑还能用吗？不如自己开个24小时试试嘛，当然，这时候您肯定又要说到让我去看您的代码，看您做了什么工作，然而我只关心卡不卡，就像tp和游戏服务器一样，我说他卡，有问题，难道我还要去看懂他的代码然后提出意见才能说话？怎么不把泥潭贴子全删了呢
> 说什么半途而废，你有你的想法，我有我的工作，我也有长期维护的代码，何必面面俱到地告诉您呢？真的非常可笑

说真的，到现在我真的怀疑你是不是心智没发育全了，感觉完全不像个正常人，唉，好可惜（可惜个屁）

**Comment by pyrokinetech** [comment]
哎呦，好可惜啊，真的好可惜啊，两句yygq就受不了了，真的很可惜啊，希望能成为一个不怕yygq的人（双手合十）  
我能占满所有核心吗，当然可以，我为了这个调试了好久，但是奈何python的多线程不支持多核，仅多进程支持，而多进程的调用没法达到预期的性能控制，于是又去掉了，真当全世界就你会写多进程吗（yygq的一句话，自己就当自己是人，老双标了），用了几十上百倍的内存跑个多进程，非常骄傲嘛，反正占得不是自己的电脑  
占满核心的另一个方法，很简单，就是用c的pthread写个计算核然后用huey来调用就完事了，异步多线程，速度快还省内存，写一个让内存无限增长的程序还觉得很ok，那我希望以后继续保持高内存占用别改哈，还是说写到3.8.1了还不会调用c？至于你说的速度问题，我最开始只说了你的内存占用问题，我本来就只想从一个非程序员的角度去说你内存占用高，结果后面扯这么远  
说不过吗，我骂街了吗，你可以引用下我哪里有脏话，反正我没改过我的贴子，当然，你觉得yygq也是脏话那我无话可说，至于一个被tx收购的xx论坛我不好多评价，版主是什么心理我哪知道，反正我的号被封了，我也不想揣测你们的动机  
本来道不同不相为谋，写到这就结了，发现你在隔壁yygq来了句【刚刚睡醒用周年庆的12券子上了13魔杖，后面战令又开出了个套装装扮，一下子就不气了，开心】，感觉这还是行家的行为嘛，这时不禁想到，你要是直接说两句我就喜欢多进程卡是你自己不会用，这个issue也就结了，结果又是拉黑，又是挂人，又是不知道哪来的封号，让我想到了一些东西，我给你表演下哈  
【你知道我们有多努力吗】  
【你知道怎么查杀外挂吗，你懂吗，你会扫描硬盘吗，你会杀毒吗，你懂内核吗】  
【这都是tp最早的开发工程师留下的问题，你去找他们啊，我是无辜的，我修不了，我无罪】  
【要不是我早知道隔壁360也会杀毒，我就去隔壁了】  
【你对我tp有意见，有本事你加入tx啊，我给你看代码，你一周内改不出来就来谢罪】  
【那么多人用我的反外挂程序，你看我还联合警方抓获了那么多工作室，我tp饱受赞誉】  
【我多进程查杀多快，也就你的几十上百倍内存占用，卡那是你不会用】  
【今天又赚的盆满钵满了，一下子就不气了】  
有丶滑稽

**Comment by fzls** [comment]
唉，为你家里人感到心疼，养活这么个娃到这么大一定很艰难。

**Comment by pyrokinetech** [comment]
我也挺同情你的

**Comment by fzls** [comment]
唉，发现了对你这种没脑子的人还是直接拉黑吧。惹不起还躲不起吗。唉，世界这么大，咋就遇到你这么个傻逼。
